### ISSUE TITLE
Standings simulator card doesn't appear on mobile

### ISSUE THREAD

**Issue by talshir** [JakePartusch/fantasy-tools#111]
On the home page. Playoff Machine & Trade Analyzer components appear as cards. The Playoff simulator card is clickable, but appears just as text on the page

Model: iPhone X
OS: 13.1.3
Browsers: chrome, safari

**Comment by JakePartusch** [comment]
Interesting... Do you have a screenshot? On Android/Chrome it looks the same as the other cards.

**Comment by talshir** [comment]
![df97960d-d9a8-443e-a591-04fe715cdf57](https://user-images.githubusercontent.com/28421177/67493403-7b83e900-f680-11e9-93af-6db3ec8b1344.jpg)

**Comment by talshir** [comment]
It seems like the CSS set on the button is interfering with its rendering. I'm gonna see what I can do to fix it
